name: Maven CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Build & test
        working-directory: airhotel
        run: mvn -B clean verify
      - name: Run PMD
        working-directory: airhotel
        run: mvn pmd:check

