name: Maven CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Build & Test
        working-directory: airhotel
        run: mvn -B clean verify
      - name: Generate Code Coverage
        working-directory: airhotel
        run: mvn jacoco:report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: airhotel/target/site/jacoco
      - name: Run PMD
        working-directory: airhotel
        run: mvn pmd:check
